### ISSUE TITLE
Add class to input when dropdown is active

### ISSUE THREAD

**Issue by AlecRust** [alphagov/accessible-autocomplete#384]
I'm working with inputs that have a border radius:

![screenshot](https://i.imgur.com/yshXPqV.png)

And when the results are open I'd like to remove the bottom border radius from the input, to achieve:

![screenshot](https://i.imgur.com/fS9EEGd.png)

However, there doesn't seem to be a class on the input when the results panel is open for me to do this.

The `aria-expanded` attribute does change when the results panel is open, but **not when the panel is open for the "no results" message**. So this only half works:

```css
.autocomplete__input[aria-expanded=true] {
  border-bottom-left-radius: 0;
  border-bottom-right-radius: 0;
}
```

This seems like a pretty common use case that could warrant adding a class for? Or perhaps `aria-expanded` should be set to `true` when the results panel is expanded showing "No results"?
